const ActionTypes = {
  SELECT_CATEGORY: 'SELECT_CATEGORY',
  GET_CATEGORY: 'GET_CATEGORY',
  SELECT_LETTER: 'SELECT_LETTER',
  RESET_LETTERS: 'RESET_LETTERS',
  UPDATE_GRID: 'UPDATE_GRID',
};

export default ActionTypes;
